### ISSUE TITLE
Is there a way resolve the Pending promise being returned?

### ISSUE THREAD

**Issue by bdougie** [sotojuan/is-pokemon-go-up#2]
The README provides clear instructions on how to output the result to the console, but I would like to set the output to a variable, however it returns a Pending Promise.

```js
var value
isPokemonGoUp().then(function(res) {
    value = res
})

console.log(value)
//=> Promise { Pending }
```

Is there a way around this?

**Comment by driannaude** [comment]
The whole point of Promises is that they're asynchronous. What you can probably do, however, is wrap continuing code in a function that get's called when the promise resolves and/or rejects.

``` javascript
function continueFn(value){
  // rest of your code here, promise return should 
  // be accessible via the value variable here.
}
isPokemonGoUp().then(function(res) {
    continueFn(res);
}, function(error){
  // remember to handle uncaught exceptions/errors.
})
```

**Comment by sotojuan** [comment]
Thanks @driannaude for the explanation—that about covers it.

**Comment by bdougie** [comment]
Thanks all. Promise always confuse me 💯  I also threw this together using this library https://www.ispokemon.live/
