### ISSUE TITLE
Error! On Raspbarry Pi + Mac

### ISSUE THREAD

**Issue by trilleplay** [sotojuan/is-pokemon-go-up#5]
Hello I tried to install your AWESOME npm package but i get the following errors when i execute the npm install command! :
---------------------------------------------------------------------------------
npm ERR! Linux 4.4.11-v7+
npm ERR! argv "/home/pi/.nvm/versions/node/v5.0.0/bin/node" "/home/pi/.nvm/versions/node/v5.0.0/bin/npm" "i" "is-pokemon-go-up"
npm ERR! node v5.0.0
npm ERR! npm  v3.3.6
npm ERR! code ENOSELF

npm ERR! Refusing to install is-pokemon-go-up as a dependency of itself
npm ERR! 
npm ERR! If you need help, you may report this error at:
npm ERR!     <https://github.com/npm/npm/issues>

npm ERR! Please include the following file with any support request:
npm ERR!     /home/pi/Desktop/is-pokemon-go-up/npm-debug.log
---------------------------------------------------------------------------------
Please Fix!

**Comment by sotojuan** [comment]
Hey! You're installing the module inside a folder/project also named `is-pokemon-go-up` so npm is freaking out. Try changing the folder name! Thanks for the kind words.

**Comment by trilleplay** [comment]
It Does not help still getting the same error :(

**Comment by trilleplay** [comment]
i managed to make it work with the cli version however! Great Tool!

**Comment by sotojuan** [comment]
Hm that's weird. Is there a `package.json` file inside the folder? Change the name there too if so. If not, not sure as that's the only time I've gotten that npm error. Maybe ask an npm person or look in their docs?

Thanks again for the kind words!

**Comment by trilleplay** [comment]
Thank You Im Going to try fixing it!
